# Generated by Django 6.0.1 on 2026-01-24 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва категорії')),
                ('age_limit', models.PositiveIntegerField(default=3, verbose_name='Вікові обмеження')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва фільму')),
                ('description', models.TextField(blank=True, default=None, max_length=1000, null=True, verbose_name='Опис фільму')),
                ('rating', models.DecimalField(decimal_places=1, default=5, max_digits=2, verbose_name='Рейтинг фільму')),
                ('timing', models.PositiveIntegerField(verbose_name='Тривалість фільму у хвилинах')),
                ('quality', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Якість')),
                ('release', models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата виходу')),
                ('poster', models.ImageField(blank=True, default=None, null=True, upload_to='.', verbose_name='Постер')),
                ('actors', models.ManyToManyField(to='Films.actor', verbose_name='Актори')),
                ('categories', models.ManyToManyField(to='Films.category', verbose_name='Категорії')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField(max_length=5000, verbose_name='Відгук')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Оцінка')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата відгуку')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Films.film', verbose_name='Фільм')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
        ),
    ]
