# Generated by Django 5.2.7 on 2025-10-12 09:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=16)),
                ('email', models.EmailField(blank=True, default=None, max_length=200, null=True)),
                ('address', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('bio', models.TimeField(blank=True, default=None, null=True)),
                ('age', models.IntegerField(blank=True, default=None, null=True)),
                ('profile_picture', models.ImageField(blank=True, default=None, null=True, upload_to='.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
