# Generated by Django 5.2.7 on 2025-10-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PhoneBook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='bio',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
