"""Initial migration4

Revision ID: d41bb417c8ee
Revises: 
Create Date: 2024-12-31 11:21:12.340053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd41bb417c8ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_isvalid', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('email_pass_validator', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email_pass_validator')
        batch_op.drop_column('email_isvalid')

    # ### end Alembic commands ###
