"""Init

Revision ID: 689b104d6269
Revises: 
Create Date: 2025-02-16 12:37:00.043807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '689b104d6269'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_tour_assoc', schema=None) as batch_op:
        batch_op.drop_constraint('user_tour_assoc_tour_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_tour_assoc_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='cascade')
        batch_op.create_foreign_key(None, 'tours', ['tour_id'], ['id'], ondelete='cascade')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('user_tour_assoc', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_tour_assoc_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('user_tour_assoc_tour_id_fkey', 'tours', ['tour_id'], ['id'])

    # ### end Alembic commands ###
