PRODUCTS = "files/products.txt"
PRODUCTS_SOLD = "files/products_sold.txt"
HELP = "files/help.txt"
REVIEWS = "files/reviews.json"
EMPLOYEES = "files/employees.json"
LOG = "files/log.json"
USING_COMMANDS = "files/using_commands.json"
