# Generated by Django 6.0 on 2026-01-03 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='.', verbose_name='Фото проекту')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.URLField(help_text='Введіть посилання GitHub проекту', max_length=255, verbose_name='Посилання на проект')),
                ('description', models.TextField(default=None, help_text='Опишіть Ваш проект', null=True, verbose_name='Опис проекту')),
                ('name', models.CharField(help_text='Введіть назву свого проекту', max_length=255, verbose_name='Назва проекту')),
                ('dockerhub', models.URLField(default=None, help_text='Введіть посилання DocketHub контейнера зі своїм проектом (за бажанням)', max_length=255, null=True, verbose_name='Посилання на DockerHub')),
                ('pictures', models.ManyToManyField(to='Project.picture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
