help = "files/help.txt"
products = "files/products.txt"
reviews = "files/reviews.txt"
employees = "files/employees.json"
products_sold = "files/products_sold.json"
log = "files/log.json"
most_using_command = "files/most_using_command.json"