# Generated by Django 5.2.8 on 2025-12-12 16:32

import SixSeven_RandomVPN.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('list_of_service', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('locations', models.ManyToManyField(to='SixSeven_RandomVPN.location')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipv_4_ext', models.GenericIPAddressField(default=None, null=True, unique=True)),
                ('ipv_4_int', models.GenericIPAddressField(default=None, null=True, unique=True)),
                ('ipv_6', models.GenericIPAddressField(default=None, null=True, unique=True)),
                ('exp_time', models.DateTimeField(default=SixSeven_RandomVPN.models.create_time_exp)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ManyToManyField(to='SixSeven_RandomVPN.subscription')),
                ('subscription_active', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription_active', to='SixSeven_RandomVPN.subscription')),
            ],
        ),
    ]
