# Generated by Django 5.2.8 on 2025-12-12 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SixSeven_RandomVPN', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='subscription',
            field=models.ManyToManyField(related_name='subs', to='SixSeven_RandomVPN.subscription'),
        ),
    ]
