# Generated by Django 5.2.7 on 2025-10-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeetingPlaner', '0002_planer_unique_contact_date_planer_unique_user_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='planer',
            name='accept',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
