# Generated by Django 5.2.7 on 2025-10-26 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PhoneBook', '0002_alter_contact_bio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Planer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('date', models.DateTimeField()),
                ('url', models.URLField(blank=True, default=None, null=True)),
                ('place', models.CharField(default='Online')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PhoneBook.contact')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
