# Generated by Django 5.2.7 on 2025-10-26 10:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MeetingPlaner', '0001_initial'),
        ('PhoneBook', '0002_alter_contact_bio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='planer',
            constraint=models.UniqueConstraint(fields=('contact', 'date'), name='unique_contact_date'),
        ),
        migrations.AddConstraint(
            model_name='planer',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_user_date'),
        ),
    ]
