# Generated by Django 6.0 on 2026-01-03 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default=None, help_text='Введіть номер телефону', max_length=20, null=True, verbose_name='Номер телефону')),
                ('bio', models.TextField(default=None, help_text='Опиши свій досвід', null=True, verbose_name='Інформація про себе')),
                ('avatar', models.ImageField(default=None, help_text='Вибери своє фото', null=True, upload_to='.', verbose_name='Фото профілю')),
                ('telegram', models.CharField(default=None, help_text="Має починатись із символа '@'", max_length=50, null=True, verbose_name='Нік у телеграм')),
                ('viber', models.CharField(default=None, help_text="Введіть номер телефону viber для зв'язку", max_length=20, null=True, verbose_name='Номер телефону у viber')),
                ('github', models.URLField(default=None, help_text='Введіть посиланя на профіль GitHub', max_length=255, null=True, verbose_name='Посилання на профіль у GitHub')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
