"""add description by cabinet

Revision ID: c0dbe27e3ba3
Revises: 0117e0c816c0
Create Date: 2025-10-19 20:22:52.974098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0dbe27e3ba3'
down_revision: Union[str, Sequence[str], None] = '0117e0c816c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cabinets', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cabinets', 'description')
    # ### end Alembic commands ###
