# Generated by Django 6.0 on 2025-12-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Додаткова інформація'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reason',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Інформація від адміністратора/модератора'),
        ),
    ]
